spring.application.name=resume-builder
server.port=${PORT:8080}
spring.datasource.url=jdbc:h2:file:./data/resumedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Security
spring.security.user.name=admin
spring.security.user.password=admin

# SambaNova Cloud API
sambanova.api.key=9c2b249e-063e-4bce-b8a3-bc0be5fe8387
sambanova.api.url=https://api.sambanova.ai/v1/chat/completions

# Multipart Properties
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
